"""empty message

Revision ID: 424710ae5fbb
Revises: 44a3e492f817
Create Date: 2021-07-18 03:35:01.380348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424710ae5fbb'
down_revision = '44a3e492f817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=300), nullable=True))
    op.drop_column('Artist', 'abc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('abc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
