"""empty message

Revision ID: 4299bba4ea9c
Revises: 349fe4a93ec1
Create Date: 2021-07-18 15:18:06.547371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4299bba4ea9c'
down_revision = '349fe4a93ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
